name: Shell

on:
  - push

jobs:
  test1:
    name: Shell with single quotes (Node.js v${{ matrix.node }} on ${{ matrix.os }})
    strategy:
      fail-fast: false
      matrix:
        node:
          - 10
          - 12
          - 14
          - 15
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: Shell with single quotes
        run: npx prettier --check 'test/file.js' 'test/{file}.js' 'test/file with spaces.js'

  test2:
    name: Shell with double quotes (Node.js v${{ matrix.node }} on ${{ matrix.os }})
    strategy:
      fail-fast: false
      matrix:
        node:
          - 10
          - 12
          - 14
          - 15
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: Shell with single quotes
        run: npx prettier --check "test/file.js" "test/{file}.js" "test/file with spaces.js"

  test3:
    name: Shell with escaped chars (Node.js v${{ matrix.node }} on ${{ matrix.os }})
    strategy:
      fail-fast: false
      matrix:
        node:
          - 10
          - 12
          - 14
          - 15
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: Shell with single quotes
        run: npx prettier --check test\/file.js test\/\{file\}.js test\/file\ with\ spaces.js

  test4:
    name: Shell with unescaped chars (Node.js v${{ matrix.node }} on ${{ matrix.os }})
    strategy:
      fail-fast: false
      matrix:
        node:
          - 10
          - 12
          - 14
          - 15
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: Shell with single quotes
        run: npx prettier --check test/file.js test/{file}.js test/file with spaces.js
