name: Shell

on:
  - push

jobs:
  test1:
    name: Shell with single quotes (${{ matrix.os }})
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Shell with single quotes
        run: npx prettier --check 'test/file.js' 'test/{file}.js' 'test/file with spaces.js'

  test2:
    name: Shell with double quotes (${{ matrix.os }})
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Shell with single quotes
        run: npx prettier --check "test/file.js" "test/{file}.js" "test/file with spaces.js"

  test3:
    name: Shell with escaped chars (${{ matrix.os }})
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Shell with single quotes
        run: npx prettier --check test\/file.js test\/\{file\}.js test\/file\ with\ spaces.js
